/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{js,jsx,ts,tsx}",
    "./src/app/**/*.{js,jsx,ts,tsx}",
    "./components/**/*.{js,jsx,ts,tsx}",
  ],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        canvas: "#0c0816",
        ink: "#f6f1ff",
        "ink-dim": "rgba(246, 241, 255, 0.7)",
        "ink-soft": "rgba(246, 241, 255, 0.45)",
        "on-bright": "#2a1248",
        pink: "#f0abfc",
        "pink-deep": "#e879f9",
        violet: "#a78bfa",
        lilac: "#c4b5fd",
        indigo: "#818cf8",
        sky: "#7dd3fc",
        rose: "#fda4af",
        gold: "#fcd34d",
        panel: "rgba(255, 255, 255, 0.04)",
        "panel-line": "rgba(255, 255, 255, 0.08)",
        hairline: "rgba(255, 255, 255, 0.07)",
      },
      fontFamily: {
        serif: ["InstrumentSerif_400Regular"],
        "serif-italic": ["InstrumentSerif_400Regular_Italic"],
        sans: ["Geist_400Regular"],
        "sans-light": ["Geist_300Light"],
        "sans-medium": ["Geist_500Medium"],
        "sans-semibold": ["Geist_600SemiBold"],
        "sans-bold": ["Geist_700Bold"],
        mono: ["GeistMono_400Regular"],
        "mono-medium": ["GeistMono_500Medium"],
      },
      borderRadius: {
        field: "12px",
        row: "14px",
        tile: "16px",
        card: "18px",
        fab: "20px",
        glass: "22px",
        tabbar: "28px",
      },
    },
  },
  plugins: [],
};
